print('hello Dan 5')
print('hello Dan 6')
print('hello Dan 7')print('hello Dan 5')
print('hello Dan 6')
print('hello Dan 7')print('hello Dan 5')
print('hello Dan 6')
print('hello Dan 7')print('hello Dan 5')
print('hello Dan 6')
print('hello Dan 7')print('hello Dan 5')
print('hello Dan 6')
print('hello Dan 7')print('hello Dan 5')
print('hello Dan 6')
print('hello Dan 7')print('hello Dan 5')
print('hello Dan 6')
print('hello Dan 7')print('hello Dan 5')
print('hello Dan 6')
print('hello Dan 7')print('hello Dan 5')
print('hello Dan 6')
print('hello Dan 7')print('hello Dan 5')
print('hello Dan 6')
print('hello Dan 7')print('hello Dan 5')
print('hello Dan 6')
print('hello Dan 7')print('hello Dan 5')
print('hello Dan 6')
print('hello Dan 7')print('hello Dan 5')
print('hello Dan 6')
print('hello Dan 7')
